import type { Metadata } from "next";
import LocalFont from "next/font/local";
import { cn } from "@/utils/cn";
import "./globals.css";

const font = LocalFont({ src: "../public/fonts/Alibaba-Regular.ttf" });

export const metadata: Metadata = {
   title: "Asia Startup UI Task",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className="h-full">
         <body className={cn("relative h-full", font.className)}>
            <main className="relative flex flex-col min-h-screen">{children}</main>
         </body>
      </html>
   );
}
